"""initial_migration

Revision ID: d19e7f5abb9c
Revises: 
Create Date: 2025-07-16 13:00:24.036886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd19e7f5abb9c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('offer_id', sa.BigInteger(), nullable=False),
    sa.Column('info', sa.Text(), nullable=False),
    sa.Column('deal_terms', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.String(length=500), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('photo_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('offer_id')
    )
    op.create_index('idx_offer_created_at', 'offers', ['created_at'], unique=False)
    op.create_index('idx_offer_is_active', 'offers', ['is_active'], unique=False)
    op.create_index('idx_offer_is_processed', 'offers', ['is_processed'], unique=False)
    op.create_index('idx_offer_price', 'offers', ['price'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('regdate', sa.DateTime(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.BigInteger(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.offer_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('idx_notification_user_sent', 'notifications', ['user_id', 'is_sent'], unique=False)
    op.create_table('realty_filters',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('realty_type', sa.Enum('FLAT', 'HOUSE', name='realtytype'), nullable=False),
    sa.Column('apartment', sa.Boolean(), nullable=False),
    sa.Column('rooms', sa.JSON(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('address_kind', sa.String(length=100), nullable=False),
    sa.Column('min_price', sa.Integer(), nullable=True),
    sa.Column('max_price', sa.Integer(), nullable=True),
    sa.Column('no_deposit', sa.Boolean(), nullable=False),
    sa.Column('kids', sa.Boolean(), nullable=False),
    sa.Column('pets', sa.Boolean(), nullable=False),
    sa.Column('renovation', sa.JSON(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('initial_check_completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('realty_filters')
    op.drop_index('idx_notification_user_sent', table_name='notifications')
    op.drop_index('idx_notification_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('users')
    op.drop_index('idx_offer_price', table_name='offers')
    op.drop_index('idx_offer_is_processed', table_name='offers')
    op.drop_index('idx_offer_is_active', table_name='offers')
    op.drop_index('idx_offer_created_at', table_name='offers')
    op.drop_table('offers')
    # ### end Alembic commands ###
